Repository MaterializeInc/terraform-provider-materialize, pull requests merged in 2023-08, with the labels that each got.

#220 Index Column Scan
  docs/resources/index.md
  integration/index.tf
  pkg/materialize/column.go
  pkg/resources/resource_index.go
  pkg/resources/resource_index_test.go
  pkg/resources/resource_table.go
  pkg/resources/resource_table_test.go
  pkg/testhelpers/mock_scans.go
Labels: breaking change

#260 Require `target_role_name` for Default Privileges
  docs/resources/cluster_grant_default_privilege.md
  docs/resources/connection_grant_default_privilege.md
  docs/resources/database_grant_default_privilege.md
  docs/resources/schema_grant_default_privilege.md
  docs/resources/secret_grant_default_privilege.md
  docs/resources/table_grant_default_privilege.md
  docs/resources/type_grant_default_privilege.md
  pkg/materialize/privilege_default_privilege.go
  pkg/materialize/privilege_default_privilege_test.go
  pkg/resources/resource_grant_cluster_default_privilege.go
  pkg/resources/resource_grant_connection_default_privilege.go
  pkg/resources/resource_grant_database_default_privilege.go
  pkg/resources/resource_grant_schema_default_privilege.go
  pkg/resources/resource_grant_secret_default_privilege.go
  pkg/resources/resource_grant_table_default_privilege.go
  pkg/resources/resource_grant_type_default_privilege.go
Labels: breaking change

#279 add disk support to replicas and clusters
  pkg/datasources/datasource_cluster_replica.go
  pkg/materialize/cluster.go
  pkg/materialize/cluster_replica.go
  pkg/materialize/cluster_replica_test.go
  pkg/materialize/cluster_test.go
  pkg/resources/resource_cluster.go
  pkg/resources/resource_cluster_replica.go
  pkg/testhelpers/mock_scans.go
Labels: enhancement

#271 Initial webhook source setup
  docs/resources/source_webhook.md
  examples/resources/materialize_source_webhook/import.sh
  examples/resources/materialize_source_webhook/resource.tf
  integration/source.tf
  pkg/materialize/source_webhook.go
  pkg/materialize/source_webhook_test.go
  pkg/provider/acceptance_source_webhook_test.go
  pkg/provider/provider.go
  pkg/resources/resource_source_webhook.go
  pkg/resources/resource_source_webhook_test.go
Labels: new resource

#262 Support `FOR SCHEMAS` for PostgreSQL Source
  docs/resources/sink_kafka.md
  docs/resources/source_kafka.md
  docs/resources/source_load_generator.md
  docs/resources/source_postgres.md
  pkg/materialize/source_postgres.go
  pkg/materialize/source_postgres_test.go
  pkg/resources/resource_sink_kafka.go
  pkg/resources/resource_source_kafka.go
  pkg/resources/resource_source_load_generator.go
  pkg/resources/resource_source_postgres.go
  pkg/resources/schema.go
Labels: enhancement

#294 Remove Unnecessary Default Privilege Attributes
  docs/resources/cluster_grant_default_privilege.md
  docs/resources/connection_grant_default_privilege.md
  docs/resources/database_grant_default_privilege.md
  docs/resources/schema_grant_default_privilege.md
  docs/resources/secret_grant_default_privilege.md
  docs/resources/table_grant_default_privilege.md
  docs/resources/type_grant_default_privilege.md
  integration/schema.tf
  integration/secret.tf
  integration/table.tf
  integration/type.tf
  pkg/materialize/privilege_default_privilege.go
  pkg/resources/resource_grant_database_default_privilege.go
  pkg/resources/resource_grant_schema_default_privilege.go
  pkg/resources/schema.go
Labels: bug
