Repository MaterializeInc/terraform-provider-materialize, pull requests merged in 2023-11, with the labels that each got.

#346 Update Webhook Source
  docs/resources/source_webhook.md
  integration/source.tf
  pkg/materialize/generic.go
  pkg/materialize/source_webhook.go
  pkg/materialize/source_webhook_test.go
  pkg/provider/acceptance_source_webhook_test.go
  pkg/resources/resource_source_webhook.go
  pkg/resources/resource_source_webhook_test.go
Labels: enhancement, breaking change

#353 Prevent Attribute Name Leaking
  docs/resources/connection_confluent_schema_registry.md
  docs/resources/connection_kafka.md
  docs/resources/connection_postgres.md
  docs/resources/index.md
  docs/resources/sink_kafka.md
  docs/resources/source_kafka.md
  docs/resources/source_postgres.md
  docs/resources/source_webhook.md
  pkg/materialize/connection.go
  pkg/materialize/connection_kafka.go
  pkg/materialize/format_specs.go
  pkg/materialize/identifiers.go
  pkg/resources/resource_connection_confluent_schema_registry.go
  pkg/resources/resource_connection_confluent_schema_registry_test.go
  pkg/resources/resource_connection_kafka.go
  pkg/resources/resource_connection_kafka_test.go
  pkg/resources/resource_connection_postgres.go
  pkg/resources/resource_connection_postgres_test.go
  pkg/resources/resource_sink_kafka.go
  pkg/resources/resource_sink_kafka_test.go
  pkg/resources/resource_source_kafka.go
  pkg/resources/resource_source_kafka_test.go
  pkg/resources/resource_source_postgres.go
  pkg/resources/resource_source_postgres_test.go
  pkg/resources/resource_source_webhook.go
  pkg/resources/schema.go
Labels: bug, breaking change

#363 Add ForceNew for table column name changes
  pkg/provider/acceptance_table_test.go
  pkg/resources/resource_table.go
Labels: bug

#371 Raise Max Clusters Testing
  docker-compose.yml
Labels: testing

#365 Kafka Security Protocol
  docs/resources/connection_kafka.md
  integration/connection.tf
  pkg/materialize/connection_kafka.go
  pkg/materialize/connection_kafka_test.go
  pkg/resources/config.go
  pkg/resources/resource_connection_kafka.go
  pkg/resources/resource_connection_kafka_test.go
  pkg/resources/resource_role.go
Labels: enhancement

#377 TPCH All Tables
  docker-compose.yml
  docs/resources/connection_kafka.md
  integration/connection.tf
  integration/source.tf
  pkg/materialize/source_load_generator.go
  pkg/materialize/source_load_generator_test.go
  pkg/resources/resource_connection_kafka.go
  pkg/resources/resource_source_load_generator_test.go
Labels: bug

#378 Prevent Privilege Read Errors
  .github/workflows/acceptance.yml
  .github/workflows/documentation.yml
  .github/workflows/test.yml
  docker-compose.yml
  go.mod
  integration/rbac.tf
  pkg/materialize/cluster.go
  pkg/materialize/connection.go
  pkg/materialize/database.go
  pkg/materialize/materialized_view.go
  pkg/materialize/privilege.go
  pkg/materialize/privilege_default_privilege.go
  pkg/materialize/privilege_default_privilege_test.go
  pkg/materialize/privilege_system_privilege.go
  pkg/materialize/privilege_system_privilege_test.go
  pkg/materialize/privilege_test.go
  pkg/materialize/schema.go
  pkg/materialize/secret.go
  pkg/materialize/source.go
  pkg/materialize/table.go
  pkg/materialize/type.go
  pkg/materialize/view.go
  pkg/provider/provider_test.go
  pkg/resources/resource_grant.go
  pkg/resources/resource_grant_default_privilege.go
  pkg/resources/resource_grant_default_privilege_test.go
  pkg/resources/resource_grant_materialized_view_test.go
  pkg/resources/resource_grant_source_test.go
  pkg/resources/resource_grant_system_privilege.go
  pkg/resources/resource_grant_table_test.go
  pkg/resources/resource_view_grant_test.go
  pkg/testhelpers/mock_scans.go
Labels: bug

#381 Default Grant Read Unnecessary `Set`
  integration/rbac.tf
  pkg/materialize/privilege_default_privilege.go
  pkg/materialize/privilege_default_privilege_test.go
  pkg/resources/resource_grant.go
  pkg/resources/resource_grant_default_privilege.go
  pkg/resources/resource_grant_system_privilege.go
Labels: bug

#390 Allow `replication_factor` 0
  CHANGELOG.md
  integration/cluster.tf
  pkg/materialize/cluster.go
  pkg/materialize/cluster_test.go
  pkg/provider/acceptance_cluster_test.go
  pkg/resources/resource_cluster.go
  pkg/resources/resource_cluster_test.go
Labels: bug
